project:
  type: website

website:
  title: "Notes on ChatGPT and LLMs"
  open-graph:
    locale: en-US

execute:
  freeze: auto
  eval: false

comments:
  hypothesis:
    theme: classic

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    code-fold: true

  
