project:
  type: website
#  pre-render: ./prerender

website:
  title: "mysite"
  favicon: assets/safari-pinned-tab.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

#metadata-files:
#    - sidebar.yml
